stages:
  - update

update:
  stage: update
  image: docker:dind
  tags:
    - wowsh-eval-task
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - ls
    - pwd
    - cd deploy/staging
    - docker-compose --compatibility -p wowsh-eval-task -f docker-compose.yml up -d --force-recreate --build
  only:
    - master
